version: "3"
networks:
  backend:
services:
  postgres:
    container_name: postgres
    image: postgres:14.13
    environment:
      POSTGRES_DB: 'keycloak'
      POSTGRES_USER: 'keycloak'
      POSTGRES_PASSWORD: 'keycloak'
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    networks:
      - backend
  keycloak:
    container_name: keycloak
    build: 
      context: .
      dockerfile: Dockerfile
    command: start-dev --import-realm
    ports:
      - 8080:8080
      - 5005:5005
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import   
    depends_on: 
      - postgres   
    networks:
      - backend
  mockserver:
    container_name: mockserver
    image: mockserver/mockserver:5.15.0
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /mockserver/initializer.json
      SERVER_PORT: 8081
    ports:
      - 8081:8081
    volumes:
      - ./mockserver:/mockserver
    networks:
      - backend
    